version: '3.9'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
  
  db:
    image: mysql:5.7.22
    restart: always
    hostname: localhost
    environment:
      - MYSQL_DATABASE=fews
      - MYSQL_USER=root
      - MYSQL_PASSWORD=@Undercover12
      - MYSQL_ROOT_PASSWORD=@Undercover12
    volumes:
      - .dbdata:/var/lib/mysql
    ports: 
      - 3366:3306
    
    