# Generated by Django 4.1.6 on 2023-02-10 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCategory',
            new_name='CategoryProduct',
        ),
    ]
