# Generated by Django 4.1.6 on 2023-02-25 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='type_name',
        ),
    ]
