# Generated by Django 4.1.6 on 2023-02-26 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('success', 'SUCCESS')], default='pending', max_length=10, null=True),
        ),
    ]
