# Generated by Django 4.1.6 on 2023-02-26 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_transaction_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
