# Generated by Django 4.1.6 on 2023-03-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_google_provider',
            field=models.IntegerField(default=0),
        ),
    ]
