# Generated by Django 4.1.6 on 2023-04-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_is_google_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_provider',
            field=models.IntegerField(default=0),
        ),
    ]
