# Generated by Django 4.1.6 on 2023-05-02 05:54

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_is_email_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='zip_code',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
