# Generated by Django 4.1.6 on 2023-05-05 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_useraddress_address_type_useraddress_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='full_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
